from enum import StrEnum

class Regime(StrEnum):
    BULLISH_CONTROLLED = "BULLISH_CONTROLLED"
    BEARISH_CONTROLLED = "BEARISH_CONTROLLED"
    NEUTRAL_RANGE = "NEUTRAL_RANGE"
    NO_TRADE = "NO_TRADE"
    DATA_INSUFFICIENT = "DATA_INSUFFICIENT"

class CandidateStatus(StrEnum):
    EVALUATED = "EVALUATED"
    REJECTED = "REJECTED"
    ELIGIBLE = "ELIGIBLE"
    RANKED = "RANKED"
    SELECTED = "SELECTED"
    SHADOW = "SHADOW"
    OPENED = "OPENED"
    EXPIRED_UNUSED = "EXPIRED_UNUSED"
    ERROR = "ERROR"

class PositionState(StrEnum):
    CREATED = "CREATED"
    ENTRY_PENDING = "ENTRY_PENDING"
    OPEN = "OPEN"
    HOLD = "HOLD"
    PROFIT_PROTECTED = "PROFIT_PROTECTED"
    EXIT_PENDING = "EXIT_PENDING"
    CLOSED_WIN = "CLOSED_WIN"
    CLOSED_LOSS = "CLOSED_LOSS"
    CLOSED_BREAKEVEN = "CLOSED_BREAKEVEN"
    CLOSED_EXPIRED = "CLOSED_EXPIRED"
    CLOSED_DATA_FAILURE = "CLOSED_DATA_FAILURE"
    CANCELLED = "CANCELLED"
    ERROR = "ERROR"

class Direction(StrEnum):
    CALL = "call"
    PUT = "put"

class Structure(StrEnum):
    LONG_OPTION = "long-option"
    CREDIT_SPREAD = "credit-spread"

class DiagnosticCategory(StrEnum):
    CONFIGURATION = "CONFIGURATION"
    AUTHENTICATION = "AUTHENTICATION"
    NETWORK = "NETWORK"
    PROVIDER = "PROVIDER"
    DATABASE = "DATABASE"
    DISCORD = "DISCORD"
    UNIVERSE = "UNIVERSE"
    STRATEGY = "STRATEGY"
    SCANNER = "SCANNER"
    PAPER_TRADING = "PAPER_TRADING"
    LEARNING = "LEARNING"
    REPORTING = "REPORTING"
    SCHEDULER = "SCHEDULER"
    APPLICATION = "APPLICATION"
    DEPLOYMENT = "DEPLOYMENT"
